server:
  port: 8080

## Configuración de la BD
spring:
  application:
    name: banco-webflux
  data:
    mongodb:
      database: banco
      host: localhost
      port: 27017

## Configuración de open api
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
#  packages-to-exclude:
#    - com.banco.webflux.controller
